<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-Vinnie369/blob/main/More_on_NumPy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [3]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [4]:
np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [6]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [7]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [8]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[ 0.24402323, -0.71185962,  2.04656699],
        [-0.36933347,  0.67819792, -0.14104176],
        [-0.14609651, -1.26897501,  0.92244776]]),
 array([[0.64098301, 0.86523632, 0.97835662],
        [0.60753307, 0.37809275, 0.78493881],
        [0.96843013, 0.45409312, 0.16637429]]))

In [9]:
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
R = np.random.randn(5, 5)

A_sym  = 0.5 * (R + R.T)   # symmetric part
A_asym = 0.5 * (R - R.T)   # antisymmetric part

print("Original matrix R:\n", R)
print("\nSymmetric part A_sym (A_sym.T == A_sym):\n", A_sym)
print("\nAntisymmetric part A_asym (A_asym.T == -A_asym):\n", A_asym)

# Quick sanity checks
print("\nChecks:")
print("R ≈ A_sym + A_asym :", np.allclose(R, A_sym + A_asym))
print("A_sym is symmetric :", np.allclose(A_sym, A_sym.T))
print("A_asym is antisymmetric :", np.allclose(A_asym, -A_asym.T))


Original matrix R:
 [[ 0.05696402 -1.1285735   0.30633258 -1.07269577 -0.05561745]
 [ 1.01456208 -1.09297606  1.24410393 -0.86561242  0.4619976 ]
 [ 0.55466555 -0.19771677  0.47963943 -1.31118244 -0.63341694]
 [-0.81377164  0.34041297  0.04594477 -1.95961225  0.41825478]
 [-2.06225152 -1.424897    2.22831065  0.25976775 -0.56609913]]

Symmetric part A_sym (A_sym.T == A_sym):
 [[ 0.05696402 -0.05700571  0.43049906 -0.94323371 -1.05893449]
 [-0.05700571 -1.09297606  0.52319358 -0.26259973 -0.4814497 ]
 [ 0.43049906  0.52319358  0.47963943 -0.63261883  0.79744685]
 [-0.94323371 -0.26259973 -0.63261883 -1.95961225  0.33901127]
 [-1.05893449 -0.4814497   0.79744685  0.33901127 -0.56609913]]

Antisymmetric part A_asym (A_asym.T == -A_asym):
 [[ 0.         -1.07156779 -0.12416649 -0.12946207  1.00331703]
 [ 1.07156779  0.          0.72091035 -0.60301269  0.9434473 ]
 [ 0.12416649 -0.72091035  0.         -0.6785636  -1.43086379]
 [ 0.12946207  0.60301269  0.6785636   0.          0.07924352]
 [

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [11]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [12]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [13]:
"""
1. Differences between `np.matmul`, `np.dot`, `@`, and `*`

* `*`           → element‑wise multiplication (Hadamard product).
* `np.matmul`   → matrix multiplication (and "stacked" matmul for arrays with ndim > 2).
* `@`           → infix operator for matrix multiplication; behaves like `np.matmul`.
* `np.dot`      → for 1D arrays: inner product; for 2D: matrix multiplication;
                  for higher‑dimensional arrays it has slightly different broadcasting
                  rules than `matmul`.

2. Examples illustrating the differences
"""

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[10, 20],
              [30, 40]])

print("A =\n", A)
print("B =\n", B)

# Element‑wise product
print("\nElement‑wise A * B =\n", A * B)

# Matrix products (all equivalent for 2D arrays)
print("\nA @ B         =\n", A @ B)
print("np.matmul(A, B) =\n", np.matmul(A, B))
print("np.dot(A, B)    =\n", np.dot(A, B))

# 1D example: np.dot vs element‑wise *
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("\nElement‑wise x * y =", x * y)
print("np.dot(x, y) (inner product) =", np.dot(x, y))


A =
 [[1 2]
 [3 4]]
B =
 [[10 20]
 [30 40]]

Element‑wise A * B =
 [[ 10  40]
 [ 90 160]]

A @ B         =
 [[ 70 100]
 [150 220]]
np.matmul(A, B) =
 [[ 70 100]
 [150 220]]
np.dot(A, B)    =
 [[ 70 100]
 [150 220]]

Element‑wise x * y = [ 4 10 18]
np.dot(x, y) (inner product) = 32


## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [14]:
import math

In [15]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

765 ms ± 154 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [17]:
%%timeit
xs = np.linspace(0, 10, 1_000_000)
y_vec = np.sin(xs)

18.7 ms ± 3.73 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
"""
The Jupyter magic `%%timeit` runs the code in a cell many times and reports
how long it takes on average (and the best/standard deviation).

It is useful for *comparing performance* of different implementations,
such as a Python loop vs a NumPy‑vectorized version, like the `ys_loop`
and `y_vec` examples in this notebook.
"""


'\nThe Jupyter magic `%%timeit` runs the code in a cell many times and reports\nhow long it takes on average (and the best/standard deviation).\n\nIt is useful for *comparing performance* of different implementations,\nsuch as a Python loop vs a NumPy‑vectorized version, like the `ys_loop`\nand `y_vec` examples in this notebook.\n'

In [19]:
# Vectorized total energy for a harmonic oscillator:  E = T + U
# T = (1/2) m v^2,  U = (1/2) k x^2
def harmonic_energy(x, v, m=1.0, k=1.0):
    x = np.asarray(x)
    v = np.asarray(v)
    return 0.5 * m * v**2 + 0.5 * k * x**2

# Example usage (works for scalars or arrays)
xs = np.linspace(-1.0, 1.0, 5)
vs = np.linspace(-0.5, 0.5, 5)

E = harmonic_energy(xs, vs, m=1.0, k=2.0)
print("x =", xs)
print("v =", vs)
print("Total energy E =", E)


x = [-1.  -0.5  0.   0.5  1. ]
v = [-0.5  -0.25  0.    0.25  0.5 ]
Total energy E = [1.125   0.28125 0.      0.28125 1.125  ]


## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [20]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [21]:
# The eigenvalues `vals` and eigenvectors `vecs` were computed just above.
# Each column of `vecs` is an eigenvector associated with the eigenvalue
# at the same index in `vals`.

for i, lam in enumerate(vals):
    v = vecs[:, i]
    print(f"Eigenvalue λ_{i} = {lam:.6g}")
    print("Eigenvector v_{i} = ", v)
    print()

# Roughly:
# λ ≈ 0   → v ∝ (1, 1, 1)      (uniform translation)
# λ ≈ 1   → v ∝ (-1, 0, 1)     (one node)
# λ ≈ 3   → v ∝ (1, -2, 1)     (two nodes)


Eigenvalue λ_0 = 9.99658e-17
Eigenvector v_{i} =  [-0.57735027 -0.57735027 -0.57735027]

Eigenvalue λ_1 = 1
Eigenvector v_{i} =  [-7.07106781e-01  9.71445147e-17  7.07106781e-01]

Eigenvalue λ_2 = 3
Eigenvector v_{i} =  [ 0.40824829 -0.81649658  0.40824829]



## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [22]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [23]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [24]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [25]:
# Use the eigenvectors from the diatomic‑molecule stiffness matrix K
U = vecs  # columns of U are orthonormal eigenvectors

print("U =\n", U)
print("\nU @ U.T =\n", U @ U.T)
print("\nU.T @ U =\n", U.T @ U)

print("\nCheck that both are (numerically) identity:")
print("U @ U.T ≈ I:", np.allclose(U @ U.T, np.eye(2)))
print("U.T @ U ≈ I:", np.allclose(U.T @ U, np.eye(2)))


U =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

U @ U.T =
 [[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]

U.T @ U =
 [[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]

Check that both are (numerically) identity:
U @ U.T ≈ I: True
U.T @ U ≈ I: True


In [26]:
# Diagonal matrix of eigenvalues
Lambda = np.diag(vals)

left  = K @ U           # K U
right = U @ Lambda      # U Λ

print("K @ U =\n", left)
print("\nU @ Λ =\n", right)
print("\nK @ U ≈ U @ Λ :", np.allclose(left, right))

# Now check λ = U.T @ K @ U
Lambda_from_K = U.T @ K @ U
print("\nU.T @ K @ U =\n", Lambda_from_K)
print("This should be (numerically) diagonal with the eigenvalues on the diagonal:")
print("Matches np.diag(vals):", np.allclose(Lambda_from_K, Lambda))


K @ U =
 [[-4.70734562e-14 -3.46482323e+03]
 [ 4.70734562e-14  3.46482323e+03]]

U @ Λ =
 [[    0.         -3464.82322781]
 [    0.          3464.82322781]]

K @ U ≈ U @ Λ : True

U.T @ K @ U =
 [[ 3.94430453e-31  6.65719202e-14]
 [-8.69285906e-14  4.90000000e+03]]
This should be (numerically) diagonal with the eigenvalues on the diagonal:
Matches np.diag(vals): True


In [27]:
# Interpret the two normal modes of the diatomic molecule model.
print("Eigenvalues (force constants)   :", vals)
print("Eigenvectors (columns of U) =\n", U)
print()

# Mode 1: λ ≈ 0  → zero‑frequency / translation mode
mode_translation = U[:, 0]
print("Mode 1 (λ ≈ 0): translation")
print("  eigenvector ~", mode_translation, "→ atoms move *in phase* (x1 = x2).")
print("  The bond length does not change, so there is no restoring force (center‑of‑mass motion).")
print()

# Mode 2: λ ≈ 2k  → vibrational / stretching mode
mode_stretch = U[:, 1]
print("Mode 2 (λ ≈ 2k): bond‑stretching vibration")
print("  eigenvector ~", mode_stretch, "→ atoms move *out of phase* (x1 = −x2).")
print("  The distance between the atoms oscillates, giving the usual vibrational mode.")


Eigenvalues (force constants)   : [   0. 4900.]
Eigenvectors (columns of U) =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Mode 1 (λ ≈ 0): translation
  eigenvector ~ [-0.70710678 -0.70710678] → atoms move *in phase* (x1 = x2).
  The bond length does not change, so there is no restoring force (center‑of‑mass motion).

Mode 2 (λ ≈ 2k): bond‑stretching vibration
  eigenvector ~ [-0.70710678  0.70710678] → atoms move *out of phase* (x1 = −x2).
  The distance between the atoms oscillates, giving the usual vibrational mode.
